sudo: required

language: python

services:
- docker

os: linux
dist: xenial

matrix:
  include:
  - env: PYENV=3.5.9 IMAGE=python:3.5.9-slim-buster
  - env: PYENV=3.6.10 IMAGE=python:3.6.10-slim-buster
  - env: PYENV=3.7.6 IMAGE=python:3.7.6-slim-buster
  - env: PYENV=3.8.1 IMAGE=python:3.8.1-slim-buster

install:
- pip install coveralls # Need to have coveralls installed locally for after_success to run

script:
- >
  docker run
  -v $(pwd):$(pwd)
  -w $(pwd)
  -e PYENV=$PYENV
  -e IMAGE=$IMAGE
  -e KERBEROS_USERNAME=administrator
  -e KERBEROS_PASSWORD=Password01
  -e KERBEROS_REALM=example.com
  $IMAGE
  /bin/bash .travis.sh

after_success:
- coveralls
